### ISSUE TITLE
Modal closes on click.

### ISSUE THREAD

**Issue by jeremyrajan** [shama/modal-element#2]
I have tried a couple of times and I see that if the user clicks on the modal window contents, it closes. 

HTML:

```
modal.render([
  modal.html('div', { class: 'container'}, [
    modal.html('input', {name: 'username', type: 'text', placeholder: 'Username'}),
    modal.html('input', {name: 'password', type: 'password', placeholder: 'Password'}),
    modal.html('input', {name: 'email', type: 'email', placeholder: 'Email'}),
    modal.html('input', {class: 'btn', type: 'submit', value: 'Login'}),
  ])
]);
```

So, if I click on any of the contents inside the model. It closes :(. I do see that in the code, `click` event is bound to `toggle`. Any idea why?

Thank you! :)

**Comment by jeremyrajan** [comment]
I solved this by using an event listener, on the modal overlay and stopped propagating immediate execution. Something like (handler code):

```
  if (e.target.parentElement.className === 'modal' || e.target.nodeName === 'INPUT') {
    e.stopImmediatePropagation();
  }
```

:)

**Comment by shama** [comment]
I have a more reliable method for toggling now I need to implement into this element. See https://github.com/shama/fs-explorer/blob/master/lib/contextmenu.js#L8

Fairly soon I'll be updating my virtual dom elements to use [yo-yo](https://github.com/maxogden/yo-yo) instead and will make that change.

**Comment by jeremyrajan** [comment]
Awesome! cheers :)
